#!/usr/bin/env bash
# Smoke test for the macOS-only launchd agent generated by install.sh.
set -euo pipefail

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$TEST_DIR/.." && pwd)"

# shellcheck source=../install.sh
source "$REPO_DIR/install.sh" > /dev/null

SANDBOX=$(mktemp -d)
trap 'rm -rf "$SANDBOX"' EXIT

HOME="$SANDBOX"
LABEL="com.kz86n.dotfiles-doctor"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LAUNCHCTL_LOG="$SANDBOX/launchctl.log"
: > "$LAUNCHCTL_LOG"

OS_NAME="Darwin"

uname() {
  if [ "${1:-}" = "-s" ]; then
    printf '%s\n' "$OS_NAME"
  else
    command uname "$@"
  fi
}

launchctl() {
  printf '%s\n' "$*" >> "$LAUNCHCTL_LOG"
}

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

assert_log() {
  grep -Fqx "$1" "$LAUNCHCTL_LOG" || fail "launchctl was not called with: $1"
}

echo "=== Darwin: the agent is generated and bootstrapped ==="
setup_launchd > "$SANDBOX/setup.out"

[ -f "$PLIST" ] || fail "no plist at $PLIST"
grep -Fq "loaded: $LABEL" "$SANDBOX/setup.out" || fail "setup_launchd did not report a loaded agent"
assert_log "bootout gui/$(id -u)/$LABEL"
assert_log "bootstrap gui/$(id -u) $PLIST"

python3 - "$PLIST" "$HOME" "$LABEL" <<'PY'
import plistlib
import sys

path, home, label = sys.argv[1:4]
with open(path, "rb") as f:
    agent = plistlib.load(f)

expected = {
    "Label": label,
    "ProgramArguments": ["/bin/bash", f"{home}/.shell-utils/dotfiles-doctor.sh", "--notify"],
    "StartCalendarInterval": {"Weekday": 1, "Hour": 10, "Minute": 0},
    "StandardOutPath": f"{home}/Library/Logs/dotfiles-doctor.log",
    "StandardErrorPath": f"{home}/Library/Logs/dotfiles-doctor.log",
}
for key, want in expected.items():
    got = agent.get(key)
    if got != want:
        sys.exit(f"FAIL: plist {key} is {got!r}, want {want!r}")
PY

echo "=== The agent runs a doctor entry point that still exists ==="
[ -x "$REPO_DIR/.shell-utils/dotfiles-doctor.sh" ] || fail ".shell-utils/dotfiles-doctor.sh is missing or not executable"
grep -Fq 'ln -fsn "$dotfiles_dir/.shell-utils" "$HOME/.shell-utils"' "$REPO_DIR/install.sh" \
  || fail "install.sh no longer links ~/.shell-utils, so the agent path is stale"
bash -c "source '$REPO_DIR/.shell-utils/dotfiles-doctor.sh'; parse_options --notify" \
  || fail "dotfiles-doctor.sh no longer accepts --notify"

echo "=== Non-Darwin: the agent is not installed ==="
rm -f "$PLIST"
: > "$LAUNCHCTL_LOG"
OS_NAME="Linux"
setup_launchd > "$SANDBOX/linux.out"

[ ! -e "$PLIST" ] && [ ! -s "$LAUNCHCTL_LOG" ] && [ ! -s "$SANDBOX/linux.out" ] \
  || fail "setup_launchd is not a no-op outside macOS"

echo ""
echo "All tests passed!"
